### ISSUE TITLE
feature request: real time animation and others

### ISSUE THREAD

**Issue by qpik** [mgvez/jsorrery#4]
Hello,
I couldn't find any live solar system simulation and almost decided to start writing one in three.js, but I stumbled upon yours. I'd like to contibute, for now some feature requests and ideas and in future code/models/textures or planetary data if possible:

1. real time animation speed
2. all planets spinning
3. moons
4. planet's layers (core, atmosphere)

I hope I'm not beaking github etiquette, I'm a complete noob here, but I've done some (very bad) coding in two (http://free.of.pl/k/kupikowski/2B) and three (http://free.of.pl/k/kupikowski/flowerbulb/three) so I can maybe contribute to the project.

**Comment by mgvez** [comment]
I don't care much about etiquette here... 
Feel free to fork and edit the project. If you add something that you feel would be worth pulling in here, you can request a pull. I don't devote much time to the project though, as it is merely a personal project, so it might take a while before I review it. Plus, keep in mind that since it's a personal thing, I might refuse the pull just because it does not go in the direction I intend. But you are totally free to copy the project and do what you want with it.
